export const es = {
  nav: {
    home: "Inicio",
    apartments: "Apartamentos",
    amenities: "Servicios",
    gallery: "Galería",
    contact: "Contacto",
    bookNow: "Reservar Ahora"
  },
  hero: {
    subtitle: "ALOJAMIENTO DE LUJO FRENTE AL MAR",
    title: "Experimenta la Tranquilidad del Mar",
    description: "Descubre nuestra exclusiva colección de apartamentos de lujo y habitaciones de hotel frente al mar, que ofrecen comodidad incomparable y vistas impresionantes al mar.",
    bookStay: "Reserva tu Estancia",
    exploreApartments: "Explorar Apartamentos",
    scrollDown: "Desplazarse Hacia Abajo"
  },
  footer: {
    description: "Apartamentos de lujo frente al mar y habitaciones de hotel con impresionantes vistas al mar, ofreciendo la combinación perfecta de comodidad y elegancia para tus vacaciones de ensueño.",
    quickLinks: "Enlaces Rápidos",
    contact: "Contacto",
    newsletter: "Boletín",
    newsletterDesc: "Suscríbete a nuestro boletín para ofertas especiales y actualizaciones.",
    yourEmail: "Tu dirección de correo electrónico",
    subscribe: "Suscribirse",
    allRights: "Todos los derechos reservados."
  },
  bookingForm: {
    title: "Reserva tu Estancia",
    checkIn: "Fecha de Entrada",
    checkOut: "Fecha de Salida",
    adults: "Adultos",
    children: "Niños",
    adult: "Adulto",
    child: "Niño",
    selectDate: "Seleccionar fecha",
    checkAvailability: "Comprobar Disponibilidad",
    bookingConfirmed: "¡Reserva Confirmada!"
  },
  testimonials: {
    title: "Lo Que Dicen Nuestros Huéspedes",
    description: "Descubre por qué nuestros huéspedes siguen regresando a MareSereno para sus escapadas junto al mar."
  },
  notFound: {
    title: "Página No Encontrada",
    description: "No pudimos encontrar la página que buscabas. ¿Quizás tomaste un giro equivocado en el paraíso?",
    returnHome: "Volver al Inicio"
  },
  home: { welcome: { subtitle: "Bienvenido a MareSereno", title: "Alojamiento de Lujo Junto al Mar", description1: "Ubicado en la costa mediterránea virgen, MareSereno ofrece una exquisita colección de apartamentos de lujo y habitaciones de hotel.", description2: "Ya sea que busques una escapada romántica, unas vacaciones familiares o un retiro tranquilo, nuestra diversa gama de alojamientos satisface todas las preferencias y necesidades.", learnMore: "Saber Más" }, booking: { subtitle: "Reserva tu Estancia", title: "Reserva tu Escapada Perfecta", description: "Da el primer paso hacia tus vacaciones de ensueño verificando la disponibilidad y asegurando tus fechas preferidas.", benefits: ["Confirmación instantánea", "Garantía de mejor precio", "Opciones de cancelación flexibles", "Pago seguro"] }, featuredApartments: { subtitle: "Nuestro Alojamiento", title: "Apartamentos Destacados", description: "Descubre nuestras opciones de alojamiento más populares.", viewAll: "Ver Todos los Apartamentos" }, amenities: { subtitle: "Servicios del Hotel", title: "Experimenta Lo Mejor", description: "Disfruta de nuestras instalaciones y servicios premium.", features: { beachfront: { title: "Ubicación Frente al Mar", description: "Acceso directo a playas vírgenes con aguas cristalinas." }, pools: { title: "Piscinas", description: "Relájate junto a nuestras piscinas infinitas con vistas impresionantes al mar." }, restaurant: { title: "Restaurante Gourmet", description: "Disfruta de exquisita cocina local e internacional." }, wifi: { title: "Wi-Fi de Alta Velocidad", description: "Mantente conectado con internet de alta velocidad gratuito." }, bar: { title: "Bar y Café en la Playa", description: "Bebidas refrescantes y aperitivos servidos directamente en la playa." }, location: { title: "Ubicación Premium", description: "Cerca de atracciones locales, tiendas y restaurantes." } } }, cta: { title: "¿Listo Para Tus Vacaciones de Ensueño?", description: "Reserva tu estancia hoy y experimenta la combinación perfecta de lujo, comodidad y vistas impresionantes al mar.", bookNow: "Reservar Ahora" } },
  apartments: { title: "Nuestros Apartamentos y Habitaciones", subtitle: "Descubre nuestra selección de alojamiento premium.", filters: { guests: "Huéspedes", anyGuests: "Cualquier número de huéspedes", onePlus: "1+ huéspedes", twoPlus: "2+ huéspedes", threePlus: "3+ huéspedes", fourPlus: "4+ huéspedes", location: "Ubicación", allLocations: "Todas las ubicaciones", priceRange: "Rango de Precio", showing: "Mostrando", of: "de", accommodations: "alojamientos", resetFilters: "Restablecer Filtros", noMatch: "Ningún apartamento coincide con tus filtros", adjustFilters: "Intenta ajustar tus criterios de filtro para ver más opciones.", viewDetails: "Ver Detalles", features: "características", more: "más" } },
  gallery: { title: "Galería de Fotos", subtitle: "Explora nuestro paraíso junto al mar a través de imágenes cautivadoras.", filters: { all: "Todos", exterior: "Exterior", rooms: "Habitaciones", amenities: "Servicios" } },
  booking: { title: "Reserva tu Estancia", subtitle: "Completa tu reserva en unos simples pasos.", steps: { chooseRoom: "Elegir Habitación", guestDetails: "Detalles del Huésped", confirmation: "Confirmación" }, dates: { selectDates: "Seleccionar Fechas y Huéspedes", checkIn: "Fecha de Entrada", checkOut: "Fecha de Salida", adults: "Adultos", children: "Niños", adult: "Adulto", child: "Niño", selectDate: "Seleccionar fecha" }, accommodationSelect: { title: "Selecciona tu Alojamiento", guests: "Huéspedes", selected: "Seleccionado", select: "Seleccionar", continue: "Continuar" }, guestInfo: { title: "Información del Huésped", firstName: "Nombre", lastName: "Apellido", email: "Correo Electrónico", phone: "Teléfono", address: "Dirección", city: "Ciudad", zipCode: "Código Postal", country: "País", specialRequests: "Solicitudes Especiales", specialRequestsPlaceholder: "Cualquier solicitud especial o nota para tu estancia" }, payment: { title: "Información de Pago", creditCard: "Tarjeta de Crédito", payAtProperty: "Pagar en el Establecimiento", nameOnCard: "Nombre en la Tarjeta", cardNumber: "Número de Tarjeta", cardNumberPlaceholder: "0000 0000 0000 0000", expiryDate: "Fecha de Vencimiento", expiryDatePlaceholder: "MM/AA", cvc: "CVC", cvcPlaceholder: "123", payAtPropertyInfo: "Se le pedirá que proporcione una tarjeta de crédito válida a su llegada por razones de seguridad." }, summary: { title: "Resumen de Reserva", checkIn: "Entrada", checkOut: "Salida", guests: "Huéspedes", night: "noche", nights: "noches", cleaningFee: "Tarifa de limpieza", serviceFee: "Tarifa de servicio", total: "Total" }, confirmation: { title: "Revisar Detalles de Reserva", accommodationDetails: "Detalles del Alojamiento", guestDetails: "Detalles del Huésped", name: "Nombre", email: "Correo Electrónico", phone: "Teléfono", address: "Dirección", city: "Ciudad", country: "País", specialRequests: "Solicitudes Especiales", paymentMethod: "Método de Pago", creditCard: "Tarjeta de Crédito", priceSummary: "Resumen de Precio", termsAgree: "Acepto los", termsLink: "Términos y Condiciones", privacyLink: "Política de Privacidad", cancellationInfo: "Entiendo que mi reserva está sujeta a la política de cancelación de la propiedad.", back: "Atrás", confirmBooking: "Confirmar Reserva", success: "¡Reserva Confirmada!", emailSent: "Tu reserva ha sido confirmada con éxito. Se ha enviado un correo de confirmación a", bookingReference: "Referencia de Reserva", returnToHome: "Volver al Inicio" } },
  contact: { title: "Contáctanos", subtitle: "Estamos aquí para hacer tu estancia inolvidable.", getInTouch: "Ponte en Contacto", address: "Dirección", phone: "Teléfono", email: "Correo Electrónico", receptionHours: "Horario de Recepción", checkInTime: "Entrada: Después de las 15:00", checkOutTime: "Salida: Antes de las 11:00", sendMessage: "Envíanos un Mensaje", fullName: "Nombre Completo", phoneNumber: "Número de Teléfono", subject: "Asunto", message: "Mensaje", howCanWeHelp: "¿Cómo podemos ayudarte?", send: "Enviar Mensaje", messageSent: "¡Mensaje Enviado!", thankYou: "Gracias por contactarnos.", faq: "Preguntas Frecuentes", faqSubtitle: "Encuentra respuestas rápidas a preguntas comunes.", questions: { checkInOut: { question: "¿Cuáles son los horarios de entrada y salida?", answer: "La entrada es desde las 15:00 y la salida hasta las 11:00." }, parking: { question: "¿Hay estacionamiento disponible?", answer: "Sí, ofrecemos estacionamiento gratuito para todos los huéspedes." }, pets: { question: "¿Se permiten mascotas?", answer: "Damos la bienvenida a mascotas en apartamentos designados." }, breakfast: { question: "¿El desayuno está incluido?", answer: "El desayuno está incluido en paquetes seleccionados." }, transfers: { question: "¿Ofrecen traslados al aeropuerto?", answer: "Sí, ofrecemos traslados al aeropuerto por un cargo adicional." }, amenities: { question: "¿Qué servicios están disponibles?", answer: "Nuestra propiedad cuenta con piscinas, spa, restaurantes, bar en la playa y acceso directo a la playa." } } },
  apartmentDescriptions: { "1": { name: "Suite Deluxe con Vista al Mar", description: "Suite lujosa con vista panorámica al mar." }, "2": { name: "Apartamento Premium Familiar", description: "Apartamento espacioso ideal para familias." }, "3": { name: "Estudio Ejecutivo en la Playa", description: "Elegante estudio con acceso directo a la playa." }, "4": { name: "Suite Penthouse de Lujo", description: "Suite exclusiva en el último piso." }, "5": { name: "Habitación Doble Clásica", description: "Habitación de hotel confortable." }, "6": { name: "Apartamento con Vista al Jardín", description: "Apartamento tranquilo rodeado de jardines." } },
  amenitiesPage: { title: "Nuestros Servicios", subtitle: "Descubre los servicios de lujo que hacen tu estancia inolvidable.", description: "En MareSereno, nos dedicamos a proporcionar una experiencia de estancia completa y lujosa.", categories: { wellness: { title: "Bienestar y Relajación", description: "Disfruta de nuestros servicios de bienestar.", items: [{ title: "Spa de Lujo", description: "Nuestro spa ofrece una gama completa de tratamientos." }, { title: "Centro de Fitness", description: "Mantén tu rutina de fitness con nuestro gimnasio de última generación." }, { title: "Piscina Infinity", description: "Sumérgete en nuestra piscina infinity." }, { title: "Yoga en la Playa", description: "Únete a nuestras sesiones de yoga matutinas en la playa." }] }, dining: { title: "Gastronomía", description: "Descubre lo mejor de la cocina local e internacional.", items: [{ title: "Restaurante Gourmet", description: "Saborea platos finos preparados por nuestros chefs." }, { title: "Bar en la Playa", description: "Disfruta de cócteles refrescantes con los pies en la arena." }, { title: "Lounge Bar", description: "Relájate con una selección de vinos finos." }, { title: "Servicio de Habitaciones", description: "Disfruta de comidas gourmet en la privacidad de tu apartamento." }] }, services: { title: "Servicios Adicionales", description: "Aprovecha nuestros servicios adicionales.", items: [{ title: "Conserje 24/7", description: "Nuestro equipo de conserjes está disponible en todo momento." }, { title: "Traslados al Aeropuerto", description: "Viaja cómodamente hacia y desde el aeropuerto." }, { title: "Alquiler de Autos", description: "Explora la zona con nuestra flota de vehículos premium." }, { title: "Excursiones Guiadas", description: "Descubre atracciones locales con nuestros tours personalizados." }] }, entertainment: { title: "Entretenimiento", description: "Disfruta de una variedad de actividades recreativas.", items: [{ title: "Deportes Acuáticos", description: "Prueba una amplia gama de deportes acuáticos." }, { title: "Área de Juegos para Niños", description: "Los más pequeños pueden divertirse en nuestra área de juegos segura." }, { title: "Noches Temáticas", description: "Únete a nuestras noches temáticas semanales." }, { title: "Biblioteca y Sala de Juegos", description: "Relájate con un buen libro o disfruta de juegos de mesa." }] } } }
};
